### ISSUE TITLE
Does not compile with FSF GNAT 11 or later

### ISSUE THREAD

**Issue by damaki** [jeremiahbreeden/bullfrog#14]
I tried building Bullfrog with with recent FSF GNAT versions but I get the following compile errors (repeated multiple times in different places, but omitted here for clarity):

```
bullfrog-access_types-advanced_smart_access.ads:81:04: error: instantiation error at bullfrog-access_types-advanced_smart_access_traits.ads:63
bullfrog-access_types-advanced_smart_access.ads:81:04: error: invalid conversion, not compatible with private type "System.Address"
```

I tested with different FSF GNAT versions (obtained via Alire) and found that the error occurs in FSF GNAT 11, 12, 13, and 14. The error does not occur with FSF GNAT 10.

I found that a workaround is to use `System.Storage_Elements.Integer_Address` instead of `System.Address` for `Trait_Package_ID` as this does the same thing, but the definition of `Integer_Address` is not private.

**Comment by jere-software** [comment]
Yep thanks for the report.  I noticed that as well and filed a couple of regression bugs with GNAT devs.  They are looking into fixes.
